export default {
   SIGN_UP_ACTION: "SIGN_UP_ACTION",
   AUTH_ACTION: "AUTH_ACTION",
   LOGOUT_ACTION: "LOGOUT_ACTION",
   USER_DATA_RESPONSE: "USER_DATA_RESPONSE",
   USER_DATA_REQUEST: "USER_DATA_REQUEST",
   USER_DATA_ERROR: "USER_DATA_ERROR",

   CREATE_BOT_ACTION: "CREATE_BOT_ACTION",
   DELETE_BOT_ACTION: "DELETE_BOT_ACTION",
   GET_ALL_BOTS_ACTION: "GET_ALL_BOTS_ACTION",
   BOTS_DATA_RESPONSE: "BOTS_DATA_RESPONSE",
   BOTS_DATA_REQUEST: "BOTS_DATA_REQUEST",
   BOTS_DATA_ERROR: "BOTS_DATA_ERROR",

   GET_ALL_SCENARIES: "GET_ALL_SCENARIES",
   ADD_NEW_SCENARIO: "ADD_NEW_SCENARIO",
   EDIT_SCENARIO: "EDIT_SCENARIO",
   COPY_SCENARIO: "COPY_SCENARIO",
   DELETE_SCENARIO: "DELETE_SCENARIO",


   ADD_NEW_TRIGGER: "ADD_NEW_TRIGGER",
   ADD_NEW_TRIGGER_SUCCESS: "ADD_NEW_TRIGGER_SUCCESS",
   UPDATE_TRIGGER: "UPDATE_TRIGGER",
   DELETE_TRIGGER: "DELETE_TRIGGER",
   COPY_TRIGGER: "COPY_TRIGGER",
   UPDATE_TRIGGER_TEXT: "UPDATE_TRIGGER_TEXT",

   CHANGE_SCENARIO_ID: "CHANGE_SCENARIO_ID",
   CHANGE_SOCIAL: "CHANGE_SOCIAL",
   UPDATE_SOCIAL_IN_TRIGGER: "UPDATE_SOCIAL_IN_TRIGGER",
   UPDATE_BUTTONS_IN_TRIGGER: "UPDATE_BUTTONS_IN_TRIGGER",
   DELETE_MESSAGE_IN_TRIGGER: "DELETE_MESSAGE_IN_TRIGGER",
   SINGLE_BOT_DATA_RESPONSE: "SINGLE_BOT_DATA_RESPONSE",
   SINGLE_BOT_DATA_REQUEST: "SINGLE_BOT_DATA_REQUEST",
   SINGLE_BOT_DATA_ERROR: "SINGLE_BOT_DATA_ERROR",


   GET_ALL_AUTORIDES: "GET_ALL_AUTORIDES",
   APPEND_AUTORIDE: "APPEND_AUTORIDE",
   DELETE_AUTORIDE: "DELETE_AUTORIDE",
   GET_AUTORDIDE_LINKS: "GET_AUTORIDE_LINKS",
   AUTORIDE_RESPONSE: "AUTORIDE_RESPONSE",
   AUTORIDE_REQUEST: "AUTORIDE_REQUEST",
   AUTORIDE_ERROR: "AUTORIDE_ERROR",


   GET_ALL_BROADCASTS: "GET_ALL_BROADCASTS",
   APPEND_BROADCAST: "APPEND_BROADCAST",
   DELETE_BROADCAST: "DELETE_BROADCAST",
   UPDATE_BROADCAST: "UPDATE_BROADCAST",
   BROADCAST_RESPONSE: "BROADCAST_RESPONSE",
   BROADCAST_REQUEST: "BROADCAST_REQUEST",
   BROADCAST_ERROR: "BROADCAST_ERROR",

   GET_BOT_SETUP: "GET_BOT_SETUP",
   UPDATE_BOT_REACTIONS: "UPDATE_BOT_REACTIONS",
   UPDATE_BOT_SETUP: "UPDATE_BOT_SETUP",
   BOT_SETUP_RESPONSE: "BOT_SETUP_RESPONSE",
   BOT_SETUP_REQUEST: "BOT_SETUP_REQUEST",
   BOT_SETUP_ERROR: "BOT_SETUP_ERROR",
   EDIT_FAST_BUTTON_NAME: "ACTION.EDIT_FAST_BUTTON_NAME",

   // Mine

   GET_FACEBOOK_AUTH_URL_REQUEST: "GET_FACEBOOK_AUTH_URL_REQUEST",
   GET_FACEBOOK_AUTH_URL_SUCCESS: "GET_FACEBOOK_AUTH_URL_SUCCESS",
   GET_FACEBOOK_AUTH_URL_FAILURE: "GET_FACEBOOK_AUTH_URL_FAILURE",

   GET_VK_AUTH_URL_REQUEST: "GET_VK_AUTH_URL_REQUEST",
   GET_VK_AUTH_URL_SUCCESS: "GET_VK_AUTH_URL_SUCCESS",
   GET_VK_AUTH_URL_FAILURE: "GET_VK_AUTH_URL_FAILURE",

   GET_WA_QR_URL_REQUEST: "GET_WA_QR_URL_REQUEST",
   GET_WA_QR_URL_SUCCESS: "GET_WA_QR_URL_SUCCESS",
   GET_WA_QR_URL_FAILURE: "GET_WA_QR_URL_FAILURE",

   RESET_URL: "RESET_URL",

   GET_BOT_STATISTICS_REQUEST: "GET_BOT_STATISTICS_REQUEST",
   GET_BOT_STATISTICS_SUCCESS: "GET_BOT_STATISTICS_SUCCESS",
   GET_BOT_STATISTICS_FAILURE: "GET_BOT_STATISTICS_FAILURE",

   ADD_PAYMENT_REQUEST: "ADD_PAYMENT_REQUEST",
   ADD_PAYMENT_SUCCESS: "ADD_PAYMENT_SUCCESS",
   ADD_PAYMENT_FAILURE: "ADD_PAYMENT_FAILURE",
}
